name: cbsplit-server
services:
- name: api
  source_dir: /
  github:
    repo: your-username/cbsplit-server
    branch: main
  run_command: java -jar build/libs/cbsplit-server.jar
  environment_slug: ubuntu-18
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: PORT
    value: "8080"
  - key: CBSPLIT_API_URL
    value: "https://cbsplit-server-xxxxx.ondigitalocean.app"